# Generated by Django 5.1.3 on 2024-12-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='servings',
        ),
    ]
